COUPON_NAME = "BigBasket Chocolate & Ice Cream"
BOT_NAME = "BB Coupon Bot"
BOT_USERNAME = "FlashXBBbot"
AI_NAME = "Cutie"

BTN_JOIN_CHANNEL = "📢 Join Channel"
BTN_JOIN_GROUP = "👥 Join Support Group"
BTN_VERIFY = "⚡ Verify"
BTN_ACCEPT = "✨ Accept"
BTN_DECLINE = "🚫 Decline"

BTN_DEAL_VAULT = "🛍️ Buy Coupons"
BTN_ACCESS_LOG = "📦 My Orders"
BTN_AI_ASSIST = "✨ Ask Cutie AI"
BTN_PROFILE = "👤 My Profile"
BTN_WALLET = "💎 My Wallet"
BTN_REFERRAL = "🎁 Refer & Earn"
BTN_SUPPORT = "🛟 Support"
BTN_RAISE_TICKET = "🎫 Open Ticket"
BTN_STOCK_ALERTS = "🔔 Deal Alerts"
BTN_CONTROL_CENTER = "🛠 Control Center"

BTN_ADD_COUPON = "➕ Add Coupon"
BTN_INVENTORY = "📦 Inventory"
BTN_STATISTICS = "📊 Statistics"
BTN_USERS = "👥 Users"
BTN_PAYMENTS = "💳 Payments"
BTN_ORDERS = "📋 Orders"
BTN_EXTRACT_CODE = "Extract Coupon Code"
BTN_MAINTENANCE_ON = "Maintenance ON"
BTN_MAINTENANCE_OFF = "Maintenance OFF"
BTN_BROADCAST = "📣 Broadcast"
BTN_SETTINGS = "⚙️ Settings"
BTN_BAN_USER = "🚫 Ban User"
BTN_UNBAN_USER = "✅ Unban User"
BTN_SET_PRICE = "💰 Set Price"
BTN_DELETE_COUPON = "🗑 Delete Coupon"
BTN_TICKETS = "🎫 Tickets"
BTN_REPLY_TICKET = "💬 Reply Ticket"
BTN_WALLET_CREDIT = "💎 Add Wallet"
BTN_FLASH_SALE = "⚡ Flash Sale"
BTN_BULK_BUYER = "⭐ Bulk Buyer"
BTN_RESET_ALL = "💥 Reset All"
BTN_ANALYTICS = "📈 Analytics"
BTN_BACKUP = "📤 Backup"
BTN_AUDIT_LOGS = "🧾 Audit Logs"
BTN_MAIN_MENU = "🏠 Main Menu"
BTN_EXIT_DEVELOPER = "❌ Exit Developer Panel"

BTN_BUY_NOW = "🛒 Buy Now"
BTN_PAY_NOW = "💳 Pay Now"
BTN_CANCEL_ORDER = "❌ Cancel Order"

WELCOME_TEXT = (
    "⚡ <b>Welcome to BB Coupon Bot</b>\n\n"
    "<blockquote>Meet <b>Cutie AI</b> 💖, your premium assistant for coupons, "
    "payments, support, wallet, referrals, alerts, and order help.</blockquote>\n\n"
    "<b>Before continuing</b>\n"
    "1. 📢 Join our channel\n"
    "2. 👥 Join our support group\n"
    "3. ⚡ Press <b>Verify</b>"
)

TERMS_TEXT = (
    "✨ <b>FLASHX Terms of Use</b>\n\n"
    "<blockquote><b>Coupon Purchase Policy</b>\n"
    "All coupon sales are final. Coupons must be used before expiry.</blockquote>\n\n"
    "⚡ <b>Instant Delivery</b>\n"
    "<i>Coupons are delivered automatically after payment verification. "
    "Gateway delays may happen.</i>\n\n"
    "🛡 <b>Security and Fair Usage</b>\n"
    "Fraudulent activity, chargebacks, or abuse may result in restrictions.\n\n"
    "💳 <b>Payments</b>\n"
    "Failed payments do not generate coupons. Contact support if money is "
    "debited but delivery fails.\n\n"
    "💖 <b>Cutie AI Support</b>\n"
    "Report issues within 24 hours and keep your Order ID ready.\n\n"
    "✨ <b>By clicking ACCEPT, you agree to these terms.</b>"
)

FLASH_VERIFY_TEXT = "⚡ <b>FLASH CHECK</b>\n\n<blockquote>Cutie is verifying your access...</blockquote>"
FLASH_ACCEPT_TEXT = "✨ <b>ACCESS UNLOCKING</b>\n\n<blockquote>Cutie is preparing your premium menu...</blockquote>"
FLASH_ORDER_TEXT = "⚡ <b>ORDER FLASH</b>\n\n<blockquote>Cutie is creating your coupon order...</blockquote>"
FLASH_PAYMENT_TEXT = "💳 <b>PAYMENT FLASH</b>\n\n<blockquote>Cutie is preparing secure checkout...</blockquote>"
FLASH_CANCEL_TEXT = "🚫 <b>CANCEL FLASH</b>\n\n<blockquote>Cutie is closing this order...</blockquote>"
