const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand(); tg?.setHeaderColor?.('#10131f'); tg?.setBackgroundColor?.('#10131f');
const state={data:null,quantity:1,selected:null,watching:false};
const $=s=>document.querySelector(s); const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)};
async function api(path,options={}){let r;try{r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(options.headers||{})}})}catch(_){throw Error('Connection paused while UPI is open. Return to Telegram and the order will resume automatically.')}let d;try{d=await r.json()}catch(_){throw Error('The secure payment page is returning. Please wait a moment.')}if(!r.ok)throw Error(d.detail||'Something went wrong');return d}
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function renderHome(){const d=state.data;$('#wallet').textContent=money(d.wallet_balance);$('#order-count').textContent=d.orders.length;$('#stock-label').textContent=d.coupons.reduce((n,c)=>n+c.stock,0)+' live';$('#coupons').innerHTML=d.coupons.map((c,i)=>`<article class="coupon" style="animation-delay:${i*.05}s"><div class="coupon-top"><h3>🎟️ ${escape(c.coupon_name)}</h3><span class="pill">${c.stock} LEFT</span></div><p class="meta">💎 ₹${c.discount} OFF · Min. order ₹${c.minimum}</p><div class="coupon-bottom"><span class="price">${money(c.price)}</span><button class="buy" data-id="${c.coupon_id}">Buy now</button></div></article>`).join('')||'<p class="meta">No coupons are live right now. Check back soon.</p>';document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>openCheckout(+b.dataset.id));$('#hero-buy').onclick=()=>{const first=d.coupons[0];if(first)openCheckout(first.coupon_id);else toast('No live coupon is available right now.')}}
function escape(t){const e=document.createElement('i');e.textContent=t;return e.innerHTML}
function sheet(html){const e=$('#view');e.innerHTML=html;e.hidden=false;}
function closeSheet(){ $('#view').hidden=true; }
function openCheckout(id){state.selected=state.data.coupons.find(c=>c.coupon_id===id);state.quantity=1;checkoutSheet()}
function checkoutSheet(){const c=state.selected,q=state.quantity;sheet(`<h2>Checkout</h2><p class="meta">${escape(c.coupon_name)} · ${c.stock} available</p><div class="qty"><button id="minus">−</button><b>${q} coupon${q>1?'s':''}</b><button id="plus">+</button></div><div class="row"><span>Total</span><b>${money(c.price*q)}</b></div><button class="primary" id="pay">🔒 Continue to secure payment</button><button class="primary" id="cancel">Cancel</button>`);$('#minus').onclick=()=>{state.quantity=Math.max(1,q-1);checkoutSheet()};$('#plus').onclick=()=>{state.quantity=Math.min(c.stock,20,q+1);checkoutSheet()};$('#cancel').onclick=closeSheet;$('#pay').onclick=startPayment;}
function successSound(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=660;g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.22);o.start();o.stop(a.currentTime+.22)}catch(_){}}
async function watchOrder(id){if(state.watching)return;state.watching=true;for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,2000));try{const r=await api('/api/mini/orders/'+id+'/status');const o=r.order;if(o.delivery_status==='DELIVERED'){successSound();sheet(`<h2>🎉 Coupon delivered</h2><p class="meta">Payment confirmed. Your code is safely stored here and has also been sent in the bot chat.</p><div class="order"><b>${escape(o.coupon_name)}</b><small>🎟 Code: ${escape(o.coupon_code||'Delivered')}</small></div><button class="primary" id="view-orders">View order history</button>`);$('#view-orders').onclick=()=>{state.data.orders.unshift(o);orders()};state.data=await api('/api/mini/bootstrap');renderHome();state.watching=false;return}if(['FAILED','CANCELLED'].includes(o.payment_status)){toast('Payment was not completed.');state.watching=false;return}}catch(e){console.warn(e);toast('Waiting for the secure UPI return…')}}state.watching=false}
async function startPayment(){try{const result=await api('/api/mini/checkout',{method:'POST',body:JSON.stringify({coupon_id:state.selected.coupon_id,quantity:state.quantity})});if(result.delivered){successSound();state.data=await api('/api/mini/bootstrap');renderHome();sheet(`<h2>🎉 Coupon delivered</h2><p class="meta">Your wallet paid this order in full.</p><div class="order"><b>${escape(result.order.coupon_name)}</b><small>Code: ${escape(result.order.coupon_code||'Delivered')}</small></div>`);setTimeout(()=>tg?.close(),2200);return}const expiry=new Date(result.order.expires_at);sheet(`<h2>Opening secure checkout…</h2><p class="meta">Order ${result.order.id}</p><h1 id="timer">--:--</h1><p class="meta">Complete payment before this timer reaches zero. Your coupon is delivered automatically after payment confirmation.</p>`);const tick=()=>{const s=Math.max(0,Math.floor((expiry-Date.now())/1000));$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;if(!s){toast('Payment expired');return}setTimeout(tick,1000)};tick();if(!window.Cashfree)throw Error('Secure checkout is loading. Please try again.');Cashfree({mode:state.data.cashfree_mode==='production'?'production':'sandbox'}).checkout({paymentSessionId:result.payment_session_id,redirectTarget:'_modal'});watchOrder(result.order.id)}catch(e){toast(e.message)}}
function orders(){sheet(`<h2>My orders</h2><p class="meta">Every delivered code stays safely available here.</p>${state.data.orders.map(o=>`<div class="order"><b>${escape(o.coupon_name)} · ${money(o.amount)}</b><small>${o.id}</small><span class="status">${escape(o.payment_status)} · ${escape(o.delivery_status)}</span>${o.coupon_code?`<small>🎟 Code: ${escape(o.coupon_code)}</small>`:''}</div>`).join('')||'<p class="meta">Your paid coupons will appear here.</p>'}`)}
async function wallet(){try{const w=await api('/api/mini/wallet');sheet(`<h2>💎 My wallet</h2><h1>${money(w.balance)}</h1><p class="meta">Use wallet credit automatically at checkout.</p>${w.transactions.map(t=>`<div class="order"><b>${t.amount>=0?'+':'−'}${money(Math.abs(t.amount))}</b><small>${escape(t.reason)}</small></div>`).join('')||'<p class="meta">No transactions yet.</p>'}`)}catch(e){toast(e.message)}}
function support(){sheet(`<h2>🛟 Support</h2><p class="meta">Tell us what happened. Our team will reply in Telegram.</p><input id="subject" placeholder="Payment issue, coupon issue…"><textarea id="message" placeholder="Describe your issue"></textarea><button class="primary" id="send-ticket">Create support ticket</button>`);$('#send-ticket').onclick=async()=>{try{const r=await api('/api/mini/tickets',{method:'POST',body:JSON.stringify({subject:$('#subject').value,message:$('#message').value})});closeSheet();toast('Ticket #'+r.ticket_id+' created successfully')}catch(e){toast(e.message)}}}
async function admin(){try{const d=await api('/api/mini/admin/overview');const a=d.analytics;sheet(`<h2>🛠 Admin dashboard</h2><p class="meta">Live protected overview — customer data stays server-side.</p><div class="quick-grid"><div class="quick violet"><b>${money(a.revenue)}</b><small>Revenue</small></div><div class="quick yellow"><b>${a.total_orders}</b><small>Orders</small></div><div class="quick cyan"><b>${a.total_users}</b><small>Users</small></div></div><h3>Inventory</h3>${d.coupons.map(c=>`<div class="order"><b>${escape(c.name)}</b><small>${c.available} available · ${money(c.price)}</small></div>`).join('')||'<p class="meta">No coupon data.</p>'}<h3>Open tickets</h3>${d.tickets.map(t=>`<div class="order"><b>#${t.id} ${escape(t.subject)}</b><small>${escape(t.status)}</small></div>`).join('')||'<p class="meta">No open tickets.</p>'}`)}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]')?.dataset.nav;if(nav){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===nav));if(nav==='orders')orders();if(nav==='wallet')wallet();if(nav==='support')support();if(nav==='admin')admin();if(nav==='home')closeSheet()}const view=e.target.closest('[data-view]')?.dataset.view;if(view==='orders')orders();if(view==='wallet')wallet();if(view==='refer')toast('Share your bot link to earn referral rewards!');if(e.target.closest('#profile-btn'))toast('Your secure Telegram profile is connected.')});
(async()=>{try{state.data=await api('/api/mini/bootstrap');if(state.data.is_admin){const n=document.querySelector('nav');n.insertAdjacentHTML('beforeend','<button data-nav="admin"><span>⚙</span><small>Admin</small></button>')}$('#loading').hidden=true;$('#shop').hidden=false;renderHome();const returnedOrder=new URLSearchParams(location.search).get('order_id');if(returnedOrder){sheet('<h2>Checking payment…</h2><p class="meta">Your UPI app returned to Telegram. We are confirming the payment and delivery now.</p>');watchOrder(returnedOrder)}}catch(e){$('#loading').innerHTML='<span class="logo-mark">!</span><b>'+escape(e.message)+'</b><small>Open this shop from Telegram.</small>'}})();
