from aiogram.types import KeyboardButton, ReplyKeyboardMarkup

from texts import (
    BTN_ADD_COUPON,
    BTN_ANALYTICS,
    BTN_AUDIT_LOGS,
    BTN_BACKUP,
    BTN_BAN_USER,
    BTN_BROADCAST,
    BTN_BULK_BUYER,
    BTN_DELETE_COUPON,
    BTN_EXTRACT_CODE,
    BTN_MAINTENANCE_OFF,
    BTN_MAINTENANCE_ON,
    BTN_EXIT_DEVELOPER,
    BTN_FLASH_SALE,
    BTN_CANCEL_FLASH_SALE,
    BTN_RECONCILE_DELIVERY,
    BTN_INVENTORY,
    BTN_MAIN_MENU,
    BTN_ORDERS,
    BTN_PAYMENTS,
    BTN_REPLY_TICKET,
    BTN_SETTINGS,
    BTN_SET_PRICE,
    BTN_STATISTICS,
    BTN_TICKETS,
    BTN_UNBAN_USER,
    BTN_USERS,
    BTN_WALLET_CREDIT,
    BTN_RESET_ALL,
)


def developer_menu():
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=BTN_ADD_COUPON, style="success"), KeyboardButton(text=BTN_INVENTORY, style="primary")],
            [KeyboardButton(text=BTN_STATISTICS, style="primary"), KeyboardButton(text=BTN_ANALYTICS, style="primary")],
            [KeyboardButton(text=BTN_PAYMENTS, style="success"), KeyboardButton(text=BTN_ORDERS, style="primary")],
            [KeyboardButton(text=BTN_EXTRACT_CODE, style="primary")],
            [KeyboardButton(text=BTN_MAINTENANCE_ON, style="danger"), KeyboardButton(text=BTN_MAINTENANCE_OFF, style="success")],
            [KeyboardButton(text=BTN_BROADCAST, style="primary"), KeyboardButton(text=BTN_SETTINGS, style="primary")],
            [KeyboardButton(text=BTN_BAN_USER, style="danger"), KeyboardButton(text=BTN_UNBAN_USER, style="success")],
            [KeyboardButton(text=BTN_SET_PRICE, style="primary"), KeyboardButton(text=BTN_DELETE_COUPON, style="danger")],
            [KeyboardButton(text=BTN_TICKETS, style="primary"), KeyboardButton(text=BTN_REPLY_TICKET, style="success")],
            [KeyboardButton(text=BTN_WALLET_CREDIT, style="success"), KeyboardButton(text=BTN_FLASH_SALE, style="danger")],
            [KeyboardButton(text=BTN_CANCEL_FLASH_SALE, style="danger"), KeyboardButton(text=BTN_RECONCILE_DELIVERY, style="success")],
            [KeyboardButton(text=BTN_BULK_BUYER, style="primary")],
            [KeyboardButton(text=BTN_BACKUP, style="primary"), KeyboardButton(text=BTN_AUDIT_LOGS, style="primary")],
            [KeyboardButton(text=BTN_RESET_ALL, style="danger")],
            [KeyboardButton(text=BTN_MAIN_MENU, style="primary")],
            [KeyboardButton(text=BTN_EXIT_DEVELOPER, style="danger")],
        ],
        resize_keyboard=True,
    )
